# Generated by Django 3.2 on 2021-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0003_auto_20210417_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopreg',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='shopreg',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RemoveField(
            model_name='shopreg',
            name='place',
        ),
        migrations.AddField(
            model_name='shopreg',
            name='Place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
