# Generated by Django 3.2 on 2021-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
