# Generated by Django 3.2 on 2021-04-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0012_remove_cart_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
