# Generated by Django 3.2 on 2021-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0014_remove_cart_billstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
