# Generated by Django 3.2 on 2021-04-19 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceprovider_app', '0015_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null='True')),
                ('delivery', models.CharField(max_length=100, null='True')),
                ('prodt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider_app.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
