# Generated by Django 3.2 on 2021-04-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0017_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
