# Generated by Django 3.2 on 2021-04-20 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0023_alter_userbuy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuy',
            name='USER',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider_app.userreg'),
        ),
    ]
