# Generated by Django 3.2 on 2021-04-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0026_auto_20210421_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='USERR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider_app.userreg'),
        ),
    ]
