# Generated by Django 3.2 on 2021-04-20 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0027_alter_cart_userr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.AddField(
            model_name='feedback',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceprovider_app.userreg'),
        ),
    ]
