# Generated by Django 3.2 on 2021-04-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceprovider_app', '0028_auto_20210421_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='USER',
            new_name='USE',
        ),
    ]
